# Generated by Django 6.1.1 on 2026-09-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Foto')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Título / descripción corta')),
                ('category', models.CharField(choices=[('fachadas', 'Fachadas y Exteriores'), ('cocinas', 'Cocinas y Muebles'), ('salas-tv', 'Salas de TV'), ('pergolas', 'Pérgolas y Terrazas'), ('espejos', 'Paneles y Espejos LED'), ('quinchos', 'Quinchos y Cocinas Exteriores'), ('estructuras', 'Estructuras y Carpintería'), ('pintura', 'Pintura'), ('pavimentos', 'Pavimentos')], default='fachadas', max_length=20, verbose_name='Categoría')),
                ('placement', models.CharField(choices=[('gallery', 'Galería de portafolio'), ('hero_bg', 'Fondo del hero (portada)'), ('build_project', 'Panel "¿Qué quieres construir?" — Un proyecto nuevo'), ('build_remodel', 'Panel "¿Qué quieres construir?" — Una remodelación'), ('build_quote', 'Panel "¿Qué quieres construir?" — Una cotización')], default='gallery', max_length=20, verbose_name='Dónde se muestra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible en el sitio')),
                ('order', models.PositiveIntegerField(default=0, help_text='Menor número aparece primero.', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Subida el')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
