# Generated by Django 6.1.1 on 2026-09-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('fachadas', 'Fachadas y Exteriores'), ('cocinas', 'Cocinas y Muebles'), ('salas-tv', 'Salas de TV'), ('pergolas', 'Pérgolas y Terrazas'), ('espejos', 'Paneles y Espejos LED'), ('quinchos', 'Quinchos y Cocinas Exteriores'), ('estructuras', 'Estructuras y Carpintería'), ('pintura', 'Pintura'), ('pavimentos', 'Pavimentos'), ('remodelaciones', 'Remodelaciones')], default='fachadas', max_length=20, verbose_name='Categoría'),
        ),
    ]
